### PR TITLE
Fix vbox allowed ranges

### PR DESCRIPTION
**Pull request by r0mdau**
This PR to use the new allowed ranges for latest Virtualbox versions. My setup : 
```
$ virtualbox --help
Oracle VM VirtualBox VM Selector v6.1.32
(C) 2005-2022 Oracle Corporation
All rights reserved.

$ vagrant --version
Vagrant 2.2.19
```

The error message
```
$ vagrant up
Bringing machine 'kube-master' up with 'virtualbox' provider...
Bringing machine 'kube-worker-1' up with 'virtualbox' provider...
Bringing machine 'kube-worker-2' up with 'virtualbox' provider...
==> kube-master: Importing base box 'ubuntu/bionic64'...
==> kube-master: Matching MAC address for NAT networking...
==> kube-master: Checking if box 'ubuntu/bionic64' version '20211025.0.0' is up to date...
==> kube-master: A newer version of the box 'ubuntu/bionic64' for provider 'virtualbox' is
==> kube-master: available! You currently have version '20211025.0.0'. The latest is version
==> kube-master: '20220213.0.0'. Run `vagrant box update` to update.
==> kube-master: Setting the name of the VM: kube-master
==> kube-master: Clearing any previously set network interfaces...
The IP address configured for the host-only network is not within the
allowed ranges. Please update the address used to be within the allowed
ranges and run the command again.

  Address: 10.8.8.10
  Ranges: 192.168.56.0/21

Valid ranges can be modified in the /etc/vbox/networks.conf file. For
more information including valid format see:

  https://www.virtualbox.org/manual/ch06.html#network_hostonly
```

This PR also:
- de duplicate bash scripts
- upgrade calico manifests to v3.22
- upgrade kubernetes to v1.23.4
- fix kubernetes default version
- set kubernetes version to v1.22.0 for exercise 3

### CODE REVIEW

**Comment by r0mdau** [comment]
I have tested exercise 15. Tomorrow I am going to test exercises 2, 3, 4 and 16 to see if everything is fine.

**Comment by bmuschko** [comment]
Sounds good. Let me know. I will look over it once you feel confident that it works.

**Comment by r0mdau** [comment]
@bmuschko everything is working after a small fix.

**Comment by bmuschko** [comment]
Perfect, thanks!

**Comment by bmuschko** [comment]
@r0mdau With your changes, it seems like the internal IP is always the same for all nodes. This will definitely cause issues.

```
$ kubectl get nodes -o wide
NAME                 STATUS     ROLES                  AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
kube-control-plane   NotReady   control-plane,master   4m2s    v1.23.4   10.0.2.15     <none>        Ubuntu 18.04.6 LTS   4.15.0-166-generic   docker://19.3.14
kube-worker-1        NotReady   <none>                 2m26s   v1.23.4   10.0.2.15     <none>        Ubuntu 18.04.6 LTS   4.15.0-166-generic   docker://19.3.14
kube-worker-2        NotReady   <none>                 51s     v1.23.4   10.0.2.15     <none>        Ubuntu 18.04.6 LTS   4.15.0-166-generic   docker://19.3.14
```

Do you have thoughts on how to assign a different internal IP address per node? Happy to receive another PR. Thanks!

**Comment by r0mdau** [comment]
@bmuschko fixed here #3

**Pull request merged**
